name: build

on:
  - push
  - pull_request

jobs:
  test:
    name: "Test: Rails 7.2 on Ruby 3.3"
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    env:
      DISPLAY: ":99.0"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Ruby Version
        run: ruby --version

      - name: Run Tests
        run: bundle exec rake test
